### ISSUE TITLE
Added a test

### ISSUE THREAD

**Issue by kkhnifes** [Teaching-HTL-Leonding/robot-maze-quiz-KhnifesKyrillus#1]
@rstropek all test are green and I wrote an efficiency test which doesn't work with our random solution. I think I deserve an extra point.

**Comment by rstropek** [comment]
You get it. Just two comments:

* **Avoid** checking in binaries (e.g. dll, pdb, cache)
* In practice, **consider** https://github.com/dotnet/BenchmarkDotNet for creating benchmarks
